<?php

return [
    'providers' => [
            'BCA',
            'Mandiri',
            'BNI',
            'BRI',
            'CIMB Niaga',
            'Permata',
            'Danamon',
            'Gopay',
            'OVO',
            'DANA',
            'ShopeePay',
            'Bank Jago',
            'Bank BJB',
            'Bank Mega',
            'BSI',
            'Bank ANZ Indonesia',
            'Bank Muamalat',
            'Citibank Indonesia',
            'HSBC Indonesia',
            'Maybank Indonesia',
            'OCBC NISP',
            'Panin Bank',
            'UOB Indonesia',
            'SeaBank',
            'Jenius',
            'LinkAja',
            'Commonwealth Bank Indonesia',
            'Sinarmas Bank',
            'Blu',
            'Allo Bank',
            'Neo Commerce Bank',
            'Bank Banten',
            'Bank BSG',
            'Bank Bengkulu',
            'Bank BJB Syariah',
            'Bank BPD Bali',
            'Bank Aceh',
    ],
    'expeditions' => [
            'Self Pickup' => 'Self Pickup',
            'Paxel' => 'Paxel',
            'TIKI' => 'TIKI',
            'Shopee Express' => 'Shopee Express',
    ],
    'order_statuses' => [
            'pending'   => 'Pending',
            'process'   => 'Process',
            'shipped'   => 'Shipped',
            'returned'  => 'Returned',
            'cancel'    => 'Cancel',
    ],
    'sizes' => [
            'Fit XS' => 'Fit XS',
            'Fit S'  => 'Fit S',
            'Fit M'  => 'Fit M',
            'Fit L'  => 'Fit L',
            'Fit XL' => 'Fit XL',
            'Fit XS-S' => 'Fit XS-S',
            'Fit S-M'  => 'Fit S-M',
            'Fit M-L'  => 'Fit M-L',
            'Fit L-XL'  => 'Fit L-XL',
            'Fit XL-XXL' => 'Fit XL-XXL',
     ],
    'images' => [
        'max_size' => 3000,
        'accepted_types' => [
            'image/jpeg',
            'image/png',
            'image/webp',
            'image/gif',
        ],
    ],
    'documents' => [
        'max_size' => 5000,
        'accepted_types' => [
            'application/pdf',
            'application/msword',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document', // .docx
            'application/vnd.ms-excel',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', // .xlsx
        ],
    ]
];